on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    if: 0
    runs-on: macos-15
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: 3.10
    - run: |
        # TODO: build and publish to GH/PyPI
