on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        pyvsn: ['3.9', 'pypy3.10']
        os: ['macos-13', 'macos-14']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.pyvsn }}
    - run: python -m py.run
    - run: python -m py.dbg
  c:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
    - run: |
        make hello && ./hello
        # make translated && ./translated
